[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/bouk/monkey"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.2.1"

