[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.5.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.8"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.4"

[[constraint]]
  name = "github.com/bouk/monkey"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.4.1"

